name: The Story Photography
favicon: null
layout_spectrum: 0.75329
typography_spectrum: 0.85323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d5d5'
    - '#00babd'
    - '#000000'
    - '#00ffff'
    - '#ffffff'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
